wireplumber.settings = {
	# Store state on the filesystem
	bluetooth.use-persistent-storage = true
}

monitor.bluez.rules = [
	{
		matches = [
			{
				# Match all bluetooth devices
				device.name = "~bluez_card.*"
			}
		]

		actions = {
			update-props = {
				# Hardware volume control
				bluez5.hw-volume = []
			}
		}
	}
]
