wireplumber.settings = {
	bluetooth.use-persistent-storage = true
}

monitor.bluez.rules = [
	{
		matches = [
			{ device.name = "~bluez_card.*" }
		]
		actions = {
			update-props = {
				bluez5.hw-volume = []
			}
		}
	}
]
