## Name:    GitHub Dark
## Author:  GitHub
## License: MIT

# Basic
foreground                 #e6edf3
background                 #0d1117
selection_foreground       #0d1117
selection_background       #58a6ff

# Cursor
cursor                     #e6edf3

# Tab bar
tab_bar_background         #010409
active_tab_foreground      #c9d1d9
active_tab_background      #0d1117
inactive_tab_foreground    #8b949e
inactive_tab_background    #010409

#---------------#
#   16 colors   #
#---------------#

# Black
color0                     #000000
color8                     #6e7681

# Red
color1                     #ff7b72
color9                     #ffa198

# Green
color2                     #3fb950
color10                    #56d364

# Yellow
color3                     #d29922
color11                    #e3b341

# Blue
color4                     #58a6ff
color12                    #79c0ff

# Magenta
color5                     #bc8cff
color13                    #d2a8ff

# Cyan
color6                     #39c5cf
color14                    #56d4dd

# White
color7                     #b1bac4
color15                    #ffffff
