# https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs

device {
	name        = elan050a:01-04f3:3158-touchpad
	sensitivity = 0.20
}

device {
	name        = beken-2.4g-wireless-device-1
	sensitivity = -0.75
}
device {
	name        = beken-2.4g-wireless-device-2
	sensitivity = -0.75
}

device {
	name        = beken-usb-gaming-mouse-1
	sensitivity = -0.75
}
device {
	name        = beken-usb-gaming-mouse-2
	sensitivity = -0.75
}

# NOTE:
# > On Firefox,
# > set `mousewheel.default.delta_multiplier_y` to 100
# > set `mousewheel.min_line_scroll_amount` to 10
# > set `toolkit.scrollbox.verticalScrollDistance` to 3
