# https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs

$touchpad       = elan050a:01-04f3:3158-touchpad
$mouse_wired    = beken-2.4g-wireless-device
$mouse_wireless = beken-usb-gaming-mouse

device {
	name        = $touchpad
	sensitivity = 0.20
}

device {
	name        = $mouse_wired-1
	sensitivity = -0.75
}
device {
	name        = $mouse_wired-2
	sensitivity = -0.75
}

device {
	name        = $mouse_wireless-1
	sensitivity = -0.75
}
device {
	name        = $mouse_wireless-2
	sensitivity = -0.75
}

# NOTE:
# On Firefox,
# 	- set `mousewheel.default.delta_multiplier_y` to 100
# 	- set `mousewheel.min_line_scroll_amount` to 10
# 	- set `toolkit.scrollbox.verticalScrollDistance` to 3
