#-------------#
#   Windows   #
#-------------#
# https://wiki.hyprland.org/Configuring/Window-Rules

# Zen Browser
windowrule = float on, center on, size 595 405, match:class (zen), match:title (File Upload)

# VS Code
windowrule = float on, center on, size 1000 550, match:class (code), match:title (Save As)
windowrule = float on, center on, size 880 570, match:class (code), match:title (Open File)
windowrule = float on, center on, size 880 570, match:class (code), match:title (Open Folder)

# Nautilus
windowrule = float on, center on, size 980 640, match:class (org.gnome.Nautilus)
windowrule = float on, center on, size 375 200, border_size 0, match:class (org.gnome.Nautilus), match:title (Oops! Something went wrong.)
windowrule = float on, center on, size 510 215, border_size 0, match:class (org.gnome.Nautilus), match:title (There was an error(.*))
windowrule = float on, center on, size 300 180, border_size 0, match:class (org.gnome.Nautilus), match:title (Unable to access(.*))
windowrule = float on, center on, size 330 180, border_size 0, match:class (org.gnome.Nautilus), match:title ()

# qView
windowrule = float on, center on, size 1275 770, match:class (com.interversehq.qView)
windowrule = float on, center on, size 750 185, match:class (com.interversehq.qView), match:title (Delete)

# MPV
windowrule = float on, center on, size 1275 770, match:class (mpv)

# OBS Studio
windowrule = float on, center on, size 810 520, match:class (com.obsproject.Studio), match:title (Filters for(.*))
windowrule = float on, center on, size 1120 760, match:class (com.obsproject.Studio), match:title (Settings)
windowrule = float on, center on, size 760 395, match:class (com.obsproject.Studio), match:title (Remux Recordings)

# GTK
windowrule = float on, center on, size 885 570, match:class (xdg-desktop-portal-gtk), match:title (Open Folder)
windowrule = float on, center on, size 885 570, match:class (xdg-desktop-portal-gtk), match:title (Open File)
windowrule = float on, center on, size 985 580, match:class (xdg-desktop-portal-gtk), match:title (Save As)
windowrule = float on, center on, match:class (metadata-editor)
windowrule = float on, center on, match:title (Export Image(.*))

# Hyprland
windowrule = float on, center on, size 760 435, match:class (hyprland-share-picker)

#------------#
#   Layers   #
#------------#
# https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules

layerrule = animation fadeLayersIn, match:namespace hyprpaper

layerrule = ignore_alpha 0, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace waybar

layerrule = no_anim on, match:namespace hyprpicker
layerrule = no_anim on, match:namespace selection
