# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
	# Avoid starting multiple hyprlock instances
	lock_cmd         = pidof hyprlock || hyprlock
	# Lock before suspend
	before_sleep_cmd = loginctl lock-session
	# To avoid having to press a key twice to turn on the display
	after_sleep_cmd  = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
}

listener {
	# 2.5 minutes
	timeout    = 150
	# Set monitor backlight to minimum, avoid 0 on OLED monitor
	on-timeout = brightnessctl --save set 10%
	# Monitor backlight restore
	on-resume  = brightnessctl --restore
}

listener {
	# 3 minutes
	timeout    = 180
	# Screen off when timeout has passed
	on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'disable' })"
	# Screen on when activity is detected after timeout has fired
	on-resume  = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })" && brightnessctl --restore
}

listener {
	# 5 minutes
	timeout    = 300
	# Lock screen when timeout has passed
	on-timeout = loginctl lock-session
}

listener {
	# 10 minutes
	timeout    = 600
	# Suspend PC
	on-timeout = systemctl suspend
}

listener {
	# 30 minutes
	timeout    = 1800
	# Hibernate PC
	on-timeout = systemctl hibernate
}
