# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
	hide_cursor        = true
	ignore_empty_input = true
}

animations {
	animation = fade, 0
}

background {
	path        = ~/Pictures/wallpapers/wallpaper.jpg
	blur_passes = 2
	blur_size   = 6
	brightness  = 0.65
}

image {
	path         = ~/Pictures/personal/user.jpg
	size         = 225
	border_size  = 4
	border_color = rgba(b4befeff)
	position     = 0, 145
}

label {
	text        = $USER
	color       = rgba(b4befeff)
	font_size   = 24
	font_family = GoogleSansCode Nerd Font Medium
	position    = 0, -15
}

input-field {
	size              = 300, 40
	outline_thickness = 3
	outer_color       = rgba(b4befeff)
	inner_color       = rgba(11111bff)
	font_color        = rgba(11111bff)
	fade_on_empty     = false
	placeholder_text  =
	rounding          = 0
	check_color       = rgba(b4befeff)
	fail_color        = rgba(f38ba8ff)
	fail_text         =
	position          = 0, -100
}
