# https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

$images = ~/Downloads/images
$scripts = ~/.local/bin
$accent = rgba(b4befeff)
$black = rgba(11111bff)
$red = rgba(f38ba8ff)
$white = rgba(cdd6f4ff)
$font = CommitMono Nerd Font

animations {
	animation = fade, 0
}

general {
	hide_cursor = true
	ignore_empty_input = true
	fractional_scaling = 1
}

background {
	path = $images/wallpaper.jpg
	blur_passes = 2
	blur_size = 6
	brightness = 0.65
}

image {
	path = $images/user.jpg
	size = 225
	border_size = 5
	border_color = $accent
	position = 0, 145
}

label {
	text = $USER
	color = $accent
	font_size = 24
	font_family = $font Bold
	position = 0, -15
	halign = center
	valign = center
}

input-field {
	size = 300, 40
	outline_thickness = 4
	dots_size = 0.2
	dots_spacing = 0.40
	outer_color = $accent
	inner_color = $black
	font_color = $accent
	font_family = $font
	fade_on_empty = false
	placeholder_text = <span foreground="##9399b2">Password</span>
	rounding = 9
	check_color = $accent
	fail_color = $red
	fail_text = <span foreground="##9399b2">Password</span>
	position = 0, -100
}

# Last auth fail reason
label {
	text = $FAIL
	color = $red
	font_size = 11
	font_family = $font
	position = 0, -150
	halign = center
	valign = center
}

label {
	text = cmd[update:1000] $scripts/track truncate
	color = $white
	font_size = 12
	font_family = $font
	position = 0, -500
	halign = center
	valign = center
}
