# https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

$fg_lavender = rgba(b4befeff)
$fg_red      = rgba(f38ba8ff)
$fg_text     = rgba(cdd6f4ff)
$bg_crust    = rgba(11111bff)

$font  = CommitMono Nerd Font
$label = <span foreground="##9399b2">Password</span>

animations {
	animation = fade, 0
}

general {
	hide_cursor        = true
	ignore_empty_input = true
	fractional_scaling = 1
}

background {
	path        = ~/Downloads/images/wallpaper.jpg
	blur_passes = 2
	blur_size   = 6
	brightness  = 0.65
}

image {
	path         = ~/Downloads/images/user.jpg
	size         = 225
	border_size  = 5
	border_color = $fg_lavender
	position     = 0, 145
}

label {
	text        = $USER
	color       = $fg_lavender
	font_size   = 24
	font_family = $font Bold
	position    = 0, -15
	halign      = center
	valign      = center
}

input-field {
	size              = 300, 40
	outline_thickness = 4
	dots_size         = 0.2
	dots_spacing      = 0.40
	outer_color       = $fg_lavender
	inner_color       = $bg_crust
	font_color        = $fg_lavender
	font_family       = $font
	fade_on_empty     = false
	placeholder_text  = $label
	rounding          = 9
	check_color       = $fg_lavender
	fail_color        = $fg_red
	fail_text         = $label
	position          = 0, -100
}

# last auth fail reason
label {
	text        = $FAIL
	color       = $fg_red
	font_size   = 11
	font_family = $font
	position    = 0, -150
	halign      = center
	valign      = center
}

label {
	text        = cmd[update:1000] ~/.config/hypr/scripts/playerctl.sh
	color       = $fg_text
	font_size   = 12
	font_family = $font
	position    = 0, -500
	halign      = center
	valign      = center
}
