# https://wiki.hyprland.org/Hypr-Ecosystem/hypridle

general {
	# Avoid starting multiple hyprlock instances
	lock_cmd = pidof hyprlock || hyprlock
	# Lock before suspend
	before_sleep_cmd = loginctl lock-session
	# To avoid having to press a key twice to turn on the display
	after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
	timeout = 150
	# Set monitor backlight to minimum, avoid 0 on OLED monitor
	on-timeout = brightnessctl -s set 10%
	# Monitor backlight restore
	on-resume = brightnessctl -r
}

# Turn off keyboard backlight
listener {
	timeout = 150
	# Turn off keyboard backlight
	on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
	# Turn on keyboard backlight
	on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
	timeout = 180
	# Screen off when timeout has passed
	on-timeout = hyprctl dispatch dpms off
	# Screen on when activity is detected after timeout has fired
	on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
	timeout = 300
	# Lock screen when timeout has passed
	on-timeout = loginctl lock-session
}

listener {
	timeout = 600
	# Suspend PC
	on-timeout = systemctl suspend
}

listener {
	timeout = 1800
	# Hibernate PC
	on-timeout = systemctl hibernate
}
