#-------------#
#   Windows   #
#-------------#
# https://wiki.hypr.land/0.54.0/Configuring/Window-Rules/#window-rules

# Hyprland
windowrule = float on, center on, size 760 435, match:class (hyprland-share-picker)

# GTK
windowrule = float on, center on, size 880 570, match:class (xdg-desktop-portal-gtk), match:title (File(.*))
windowrule = float on, center on, size 880 570, match:class (xdg-desktop-portal-gtk), match:title (Open(.*))
windowrule = float on, center on, size 880 570, match:class (xdg-desktop-portal-gtk), match:title (Select(.*))
windowrule = float on, center on, size 880 570, match:class (xdg-desktop-portal-gtk), match:title (Save As(.*))

windowrule = float on, center on, match:title (Export(.*))
windowrule = float on, center on, match:class (metadata-editor)

# Nautilus
windowrule = float on, center on, size 980 640, match:class (org.gnome.Nautilus)
windowrule = float on, center on, size 375 200, border_size 0, match:class (org.gnome.Nautilus), match:title (Oops! Something went wrong.)
windowrule = float on, center on, size 510 215, border_size 0, match:class (org.gnome.Nautilus), match:title (There was an error(.*))
windowrule = float on, center on, size 300 180, border_size 0, match:class (org.gnome.Nautilus), match:title (Unable to access(.*))
windowrule = float on, center on, size 330 180, border_size 0, match:class (org.gnome.Nautilus), match:title ()

# qView
windowrule = float on, center on, size 1275 770, match:class (com.interversehq.qView)
windowrule = float on, center on, size 500 120, match:class (com.interversehq.qView), match:title (Open(.*))
windowrule = float on, center on, size 500 120, match:class (com.interversehq.qView), match:title (Delete)
windowrule = float on, center on, size 880 570, match:class (qview), match:title (Open(.*))

# MPV
windowrule = float on, center on, size 1275 770, match:class (mpv)

# OBS Studio
windowrule = float on, center on, size 1120 760, match:class (com.obsproject.Studio), match:title (Settings)
windowrule = float on, center on, size 250 120, match:class (com.obsproject.Studio), match:title (Remuxing finished)
windowrule = float on, center on, size 760 395, match:class (com.obsproject.Studio), match:title (Remux Recordings)
windowrule = float on, center on, size 810 520, match:class (com.obsproject.Studio), match:title (Filters for(.*))

#------------#
#   Layers   #
#------------#
# https://wiki.hypr.land/0.54.0/Configuring/Window-Rules/#layer-rules

layerrule = no_anim on, match:namespace hyprpicker
layerrule = no_anim on, match:namespace selection
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = animation fadeLayersIn, match:namespace hyprpaper
